export const tags = [
  { value: "Announcement", label: "Announcement" },
  { value: "Boss", label: "Boss" },
  { value: "Build", label: "Build" },
  { value: "Challenge", label: "Challenge" },
  { value: "Checklist", label: "Checklist" },
  { value: "Danger", label: "Danger" },
  { value: "Event", label: "Event" },
  { value: "Exploration", label: "Exploration" },
  { value: "Farming", label: "Farming" },
  { value: "Fun", label: "Fun" },
  { value: "Gear", label: "Gear" },
  { value: "Help", label: "Help" },
  { value: "Progress", label: "Progress" },
  { value: "Reminder", label: "Reminder" },
  { value: "Resource", label: "Resource" },
  { value: "Secret", label: "Secret" },
  { value: "Spawn", label: "Spawn" },
  { value: "Strategy", label: "Strategy" },
  { value: "To-Do", label: "To-Do" },
  { value: "Trading", label: "Trading" },
];
